/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author yungu3633
 */
import java.awt.*;        // Uses AWT's Layout Managers
import java.awt.event.*;  // Uses AWT's Event Handlers
import javax.swing.*;     // Uses Swing's Container/Components

public class Sudoku extends javax.swing.JFrame {

    /**
     * Creates new form Sudoku
     */
    public Sudoku() {
        initComponents();
        
        
        HardCodedSudokuLevels CodeofTheLevel = new HardCodedSudokuLevels();
        int [][] CorrectAnswer = CodeofTheLevel.HardCodedSudokuLevels();
        final Font FONT_NUMBERS = new Font("Monospaced", Font.BOLD, 20);
        
        JTextField[][] TT = new JTextField[9][9];
        Container cp = getContentPane();
        cp.setLayout(new GridLayout(9, 9));
        final int CANVAS_WIDTH  = 60 * 9;
        final int CANVAS_HEIGHT = 60 * 9;
        boolean[][] masks ={{false, false, false, false, false, true, false, false, false},
                            {false, false, false, false, false, false, false, false, true},
                            {false, false, false, false, false, false, false, false, false},
                            {false, false, false, false, false, false, false, false, false},
                            {false, false, false, false, false, false, false, false, false},
                            {false, false, false, false, false, false, false, false, false},
                            {false, false, false, false, false, false, false, false, false},
                            {false, false, false, false, false, false, false, false, false},
                            {false, false, false, false, false, false, false, false, false}};
        
    
        String [][] TextAreas = {{"TT00","TT01","TT02","TT03","TT04","TT05","TT06","TT07","TT08"},
                                 {"TT10","TT11","TT12","TT13","TT14","TT15","TT16","TT17","TT18"},
                                 {"TT20","TT21","TT22","TT23","TT24","TT25","TT26","TT27","TT28"},
                                 {"TT30","TT31","TT32","TT33","TT34","TT35","TT36","TT37","TT38"},
                                 {"TT40","TT41","TT42","TT43","TT44","TT45","TT46","TT47","TT48"},
                                 {"TT50","TT51","TT52","TT53","TT54","TT55","TT56","TT57","TT58"},
                                 {"TT60","TT61","TT62","TT63","TT64","TT65","TT66","TT67","TT68"},
                                 {"TT70","TT71","TT72","TT73","TT74","TT75","TT76","TT77","TT78"},
                                 {"TT80","TT81","TT82","TT83","TT84","TT85","TT86","TT87","TT88"}};
        
        for (int row = 0; row < 9; row++) {
         for (int col = 0; col < 9; col++) {
             TT[row][col] = new JTextField();
             cp.add(TT[row][col]);
             if (masks[row][col]) {
               TT[row][col].setText("");     
               TT[row][col].setEditable(true);
               
 
               
            } else {
               TT[row][col].setText(CorrectAnswer[row][col] + "");
         }
             
            TT[row][col].setHorizontalAlignment(JTextField.CENTER);
            TT[row][col].setFont(FONT_NUMBERS);
         }
    }
        
        cp.setPreferredSize(new Dimension(CANVAS_WIDTH, CANVAS_HEIGHT));
        pack();
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField28 = new javax.swing.JTextField();
        PanelGame = new javax.swing.JPanel();
        MainLableS2 = new javax.swing.JLabel();
        TT00 = new javax.swing.JTextField();
        TT01 = new javax.swing.JTextField();
        TT02 = new javax.swing.JTextField();
        TT10 = new javax.swing.JTextField();
        TT20 = new javax.swing.JTextField();
        TT11 = new javax.swing.JTextField();
        TT21 = new javax.swing.JTextField();
        TT12 = new javax.swing.JTextField();
        TT22 = new javax.swing.JTextField();
        TT03 = new javax.swing.JTextField();
        TT04 = new javax.swing.JTextField();
        TT05 = new javax.swing.JTextField();
        TT13 = new javax.swing.JTextField();
        TT14 = new javax.swing.JTextField();
        TT15 = new javax.swing.JTextField();
        TT23 = new javax.swing.JTextField();
        TT24 = new javax.swing.JTextField();
        TT25 = new javax.swing.JTextField();
        TT06 = new javax.swing.JTextField();
        TT07 = new javax.swing.JTextField();
        TT08 = new javax.swing.JTextField();
        TT16 = new javax.swing.JTextField();
        TT17 = new javax.swing.JTextField();
        TT18 = new javax.swing.JTextField();
        TT26 = new javax.swing.JTextField();
        TT27 = new javax.swing.JTextField();
        TT28 = new javax.swing.JTextField();
        TT30 = new javax.swing.JTextField();
        TT31 = new javax.swing.JTextField();
        TT32 = new javax.swing.JTextField();
        TT40 = new javax.swing.JTextField();
        TT41 = new javax.swing.JTextField();
        TT42 = new javax.swing.JTextField();
        TT50 = new javax.swing.JTextField();
        TT51 = new javax.swing.JTextField();
        TT52 = new javax.swing.JTextField();
        TT60 = new javax.swing.JTextField();
        TT61 = new javax.swing.JTextField();
        TT62 = new javax.swing.JTextField();
        TT70 = new javax.swing.JTextField();
        TT71 = new javax.swing.JTextField();
        TT72 = new javax.swing.JTextField();
        TT80 = new javax.swing.JTextField();
        TT81 = new javax.swing.JTextField();
        TT33 = new javax.swing.JTextField();
        TT34 = new javax.swing.JTextField();
        TT35 = new javax.swing.JTextField();
        TT36 = new javax.swing.JTextField();
        TT37 = new javax.swing.JTextField();
        TT43 = new javax.swing.JTextField();
        TT44 = new javax.swing.JTextField();
        TT45 = new javax.swing.JTextField();
        TT53 = new javax.swing.JTextField();
        TT54 = new javax.swing.JTextField();
        TT55 = new javax.swing.JTextField();
        TT46 = new javax.swing.JTextField();
        TT38 = new javax.swing.JTextField();
        TT47 = new javax.swing.JTextField();
        TT48 = new javax.swing.JTextField();
        TT56 = new javax.swing.JTextField();
        TT57 = new javax.swing.JTextField();
        TT58 = new javax.swing.JTextField();
        TT82 = new javax.swing.JTextField();
        TT63 = new javax.swing.JTextField();
        TT64 = new javax.swing.JTextField();
        TT65 = new javax.swing.JTextField();
        TT73 = new javax.swing.JTextField();
        TT74 = new javax.swing.JTextField();
        TT83 = new javax.swing.JTextField();
        TT84 = new javax.swing.JTextField();
        TT75 = new javax.swing.JTextField();
        TT85 = new javax.swing.JTextField();
        TT66 = new javax.swing.JTextField();
        TT67 = new javax.swing.JTextField();
        TT68 = new javax.swing.JTextField();
        TT76 = new javax.swing.JTextField();
        TT77 = new javax.swing.JTextField();
        TT78 = new javax.swing.JTextField();
        TT86 = new javax.swing.JTextField();
        TT87 = new javax.swing.JTextField();
        TT88 = new javax.swing.JTextField();
        CheckButton = new javax.swing.JButton();
        QuitButton = new javax.swing.JButton();
        RestartButton = new javax.swing.JButton();

        jTextField28.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jTextField28.setText("9");
        jTextField28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField28ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelGame.setBackground(new java.awt.Color(153, 153, 255));

        MainLableS2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 18)); // NOI18N
        MainLableS2.setForeground(new java.awt.Color(255, 102, 102));
        MainLableS2.setText("Sudoku Master");

        TT00.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT00ActionPerformed(evt);
            }
        });

        TT01.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT01ActionPerformed(evt);
            }
        });

        TT02.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT02.setText(" ");
        TT02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT02ActionPerformed(evt);
            }
        });

        TT10.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT10ActionPerformed(evt);
            }
        });

        TT20.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT20.setText(" ");
        TT20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT20ActionPerformed(evt);
            }
        });

        TT11.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT11ActionPerformed(evt);
            }
        });

        TT21.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT21.setText(" ");
        TT21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT21ActionPerformed(evt);
            }
        });

        TT12.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT12ActionPerformed(evt);
            }
        });

        TT22.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT22.setText(" ");
        TT22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT22ActionPerformed(evt);
            }
        });

        TT03.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT03ActionPerformed(evt);
            }
        });

        TT04.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT04ActionPerformed(evt);
            }
        });

        TT05.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT05ActionPerformed(evt);
            }
        });

        TT13.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT13.setText(" ");
        TT13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT13ActionPerformed(evt);
            }
        });

        TT14.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT14.setText(" ");
        TT14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT14ActionPerformed(evt);
            }
        });

        TT15.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT15.setText(" ");
        TT15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT15ActionPerformed(evt);
            }
        });

        TT23.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT23.setText(" ");
        TT23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT23ActionPerformed(evt);
            }
        });

        TT24.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT24.setText(" ");
        TT24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT24ActionPerformed(evt);
            }
        });

        TT25.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT25.setText(" ");
        TT25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT25ActionPerformed(evt);
            }
        });

        TT06.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT06ActionPerformed(evt);
            }
        });

        TT07.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT07ActionPerformed(evt);
            }
        });

        TT08.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT08ActionPerformed(evt);
            }
        });

        TT16.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT16.setText(" ");
        TT16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT16ActionPerformed(evt);
            }
        });

        TT17.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT17.setText(" ");
        TT17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT17ActionPerformed(evt);
            }
        });

        TT18.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT18.setText(" ");
        TT18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT18ActionPerformed(evt);
            }
        });

        TT26.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT26.setText(" ");
        TT26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT26ActionPerformed(evt);
            }
        });

        TT27.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT27.setText(" ");
        TT27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT27ActionPerformed(evt);
            }
        });

        TT28.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT28.setText(" ");
        TT28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT28ActionPerformed(evt);
            }
        });

        TT30.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT30.setText(" ");
        TT30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT30ActionPerformed(evt);
            }
        });

        TT31.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT31.setText(" ");
        TT31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT31ActionPerformed(evt);
            }
        });

        TT32.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT32.setText(" ");
        TT32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT32ActionPerformed(evt);
            }
        });

        TT40.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT40.setText(" ");
        TT40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT40ActionPerformed(evt);
            }
        });

        TT41.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT41.setText(" ");
        TT41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT41ActionPerformed(evt);
            }
        });

        TT42.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT42.setText(" ");
        TT42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT42ActionPerformed(evt);
            }
        });

        TT50.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT50.setText(" ");
        TT50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT50ActionPerformed(evt);
            }
        });

        TT51.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT51.setText(" ");
        TT51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT51ActionPerformed(evt);
            }
        });

        TT52.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT52.setText(" ");
        TT52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT52ActionPerformed(evt);
            }
        });

        TT60.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT60ActionPerformed(evt);
            }
        });

        TT61.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT61ActionPerformed(evt);
            }
        });

        TT62.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT62.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT62ActionPerformed(evt);
            }
        });

        TT70.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT70.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT70ActionPerformed(evt);
            }
        });

        TT71.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT71.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT71ActionPerformed(evt);
            }
        });

        TT72.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT72.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT72ActionPerformed(evt);
            }
        });

        TT80.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT80.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT80ActionPerformed(evt);
            }
        });

        TT81.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT81.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT81ActionPerformed(evt);
            }
        });

        TT33.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT33.setText(" ");
        TT33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT33ActionPerformed(evt);
            }
        });

        TT34.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT34ActionPerformed(evt);
            }
        });

        TT35.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT35ActionPerformed(evt);
            }
        });

        TT36.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT36ActionPerformed(evt);
            }
        });

        TT37.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT37ActionPerformed(evt);
            }
        });

        TT43.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT43ActionPerformed(evt);
            }
        });

        TT44.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT44ActionPerformed(evt);
            }
        });

        TT45.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT45ActionPerformed(evt);
            }
        });

        TT53.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT53ActionPerformed(evt);
            }
        });

        TT54.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT54ActionPerformed(evt);
            }
        });

        TT55.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT55ActionPerformed(evt);
            }
        });

        TT46.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT46ActionPerformed(evt);
            }
        });

        TT38.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT38ActionPerformed(evt);
            }
        });

        TT47.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT47ActionPerformed(evt);
            }
        });

        TT48.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT48ActionPerformed(evt);
            }
        });

        TT56.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT56ActionPerformed(evt);
            }
        });

        TT57.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT57.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT57ActionPerformed(evt);
            }
        });

        TT58.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT58ActionPerformed(evt);
            }
        });

        TT82.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT82.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT82ActionPerformed(evt);
            }
        });

        TT63.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT63.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT63ActionPerformed(evt);
            }
        });

        TT64.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT64ActionPerformed(evt);
            }
        });

        TT65.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT65.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT65ActionPerformed(evt);
            }
        });

        TT73.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT73.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT73ActionPerformed(evt);
            }
        });

        TT74.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT74.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT74ActionPerformed(evt);
            }
        });

        TT83.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT83.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT83ActionPerformed(evt);
            }
        });

        TT84.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT84.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT84ActionPerformed(evt);
            }
        });

        TT75.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT75.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT75ActionPerformed(evt);
            }
        });

        TT85.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT85.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT85ActionPerformed(evt);
            }
        });

        TT66.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT66.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT66ActionPerformed(evt);
            }
        });

        TT67.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT67.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT67ActionPerformed(evt);
            }
        });

        TT68.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT68.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT68ActionPerformed(evt);
            }
        });

        TT76.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT76.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT76ActionPerformed(evt);
            }
        });

        TT77.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT77.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT77ActionPerformed(evt);
            }
        });

        TT78.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT78.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT78ActionPerformed(evt);
            }
        });

        TT86.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT86.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT86ActionPerformed(evt);
            }
        });

        TT87.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT87.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT87ActionPerformed(evt);
            }
        });

        TT88.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        TT88.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TT88ActionPerformed(evt);
            }
        });

        CheckButton.setText("Check");
        CheckButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckButtonActionPerformed(evt);
            }
        });

        QuitButton.setText("Quit");
        QuitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitButtonActionPerformed(evt);
            }
        });

        RestartButton.setText("↺");
        RestartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestartButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelGameLayout = new javax.swing.GroupLayout(PanelGame);
        PanelGame.setLayout(PanelGameLayout);
        PanelGameLayout.setHorizontalGroup(
            PanelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGameLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(PanelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelGameLayout.createSequentialGroup()
                        .addGroup(PanelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelGameLayout.createSequentialGroup()
                                .addComponent(TT60, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TT61, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TT62, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelGameLayout.createSequentialGroup()
                                .addComponent(TT70, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TT71, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TT72, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelGameLayout.createSequentialGroup()
                                .addGroup(PanelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(PanelGameLayout.createSequentialGroup()
                                            .addComponent(TT10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(TT11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(TT12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(TT13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(TT14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(TT15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(PanelGameLayout.createSequentialGroup()
                                            .addComponent(TT00, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(TT01, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(TT02, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(26, 26, 26)
                                            .addComponent(TT03, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(TT04, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(TT05, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(PanelGameLayout.createSequentialGroup()
                                            .addGroup(PanelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(PanelGameLayout.createSequentialGroup()
                                                    .addComponent(TT20, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(TT21, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(TT22, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelGameLayout.createSequentialGroup()
                                                    .addComponent(TT30, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(TT31, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(TT32, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(26, 26, 26)))
                                            .addGroup(PanelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(PanelGameLayout.createSequentialGroup()
                                                    .addComponent(TT33, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(TT34, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(TT35, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(PanelGameLayout.createSequentialGroup()
                                                    .addComponent(TT23, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(TT24, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(TT25, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(PanelGameLayout.createSequentialGroup()
                                                    .addComponent(TT43, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(TT44, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(TT45, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(PanelGameLayout.createSequentialGroup()
                                                    .addComponent(TT53, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(TT54, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(TT55, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(PanelGameLayout.createSequentialGroup()
                                                    .addComponent(TT63, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(TT64, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(TT65, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(PanelGameLayout.createSequentialGroup()
                                                    .addComponent(TT73, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(TT74, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(TT75, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(PanelGameLayout.createSequentialGroup()
                                                    .addComponent(TT83, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(TT84, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(TT85, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(PanelGameLayout.createSequentialGroup()
                                        .addComponent(TT40, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TT41, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TT42, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelGameLayout.createSequentialGroup()
                                        .addComponent(TT50, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TT51, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TT52, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelGameLayout.createSequentialGroup()
                                        .addComponent(TT80, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TT81, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TT82, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(26, 26, 26)
                                .addGroup(PanelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelGameLayout.createSequentialGroup()
                                        .addComponent(TT06, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TT07, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TT08, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelGameLayout.createSequentialGroup()
                                        .addComponent(TT16, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TT17, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TT18, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelGameLayout.createSequentialGroup()
                                        .addGroup(PanelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(TT36, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TT26, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TT46, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TT56, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TT66, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TT76, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TT86, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(PanelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(PanelGameLayout.createSequentialGroup()
                                                .addComponent(TT27, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TT28, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(PanelGameLayout.createSequentialGroup()
                                                .addComponent(TT37, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TT38, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(PanelGameLayout.createSequentialGroup()
                                                .addComponent(TT47, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TT48, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(PanelGameLayout.createSequentialGroup()
                                                .addComponent(TT57, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TT58, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(PanelGameLayout.createSequentialGroup()
                                                .addComponent(TT67, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TT68, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(PanelGameLayout.createSequentialGroup()
                                                .addComponent(TT77, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TT78, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(PanelGameLayout.createSequentialGroup()
                                                .addComponent(TT87, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TT88, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelGameLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(CheckButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(RestartButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(QuitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelGameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MainLableS2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141))
        );
        PanelGameLayout.setVerticalGroup(
            PanelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainLableS2)
                .addGap(25, 25, 25)
                .addGroup(PanelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TT00, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT06, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT07, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT08, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TT10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TT20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TT30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TT40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT48, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TT50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT56, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT57, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT58, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TT60, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT62, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT63, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT64, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT65, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT66, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT67, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT68, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TT70, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT71, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT72, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT73, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT74, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT75, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT76, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT77, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT78, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TT80, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT81, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT82, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT83, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT84, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT85, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT86, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT87, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TT88, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(PanelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckButton)
                    .addComponent(QuitButton)
                    .addComponent(RestartButton))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        TT00.getAccessibleContext().setAccessibleName("");
        TT00.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void TT00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT00ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT00ActionPerformed

    private void TT01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT01ActionPerformed

    private void TT02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT02ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT02ActionPerformed

    private void TT10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT10ActionPerformed

    private void TT20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT20ActionPerformed

    private void TT11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT11ActionPerformed

    private void TT21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT21ActionPerformed

    private void TT12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT12ActionPerformed

    private void TT22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT22ActionPerformed

    private void TT03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT03ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT03ActionPerformed

    private void TT04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT04ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT04ActionPerformed

    private void TT05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT05ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT05ActionPerformed

    private void TT13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT13ActionPerformed

    private void TT14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT14ActionPerformed

    private void TT15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT15ActionPerformed

    private void TT23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT23ActionPerformed

    private void TT24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT24ActionPerformed

    private void TT25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT25ActionPerformed

    private void TT06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT06ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT06ActionPerformed

    private void TT07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT07ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT07ActionPerformed

    private void TT08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT08ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT08ActionPerformed

    private void TT16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT16ActionPerformed

    private void TT17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT17ActionPerformed

    private void TT18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT18ActionPerformed

    private void TT26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT26ActionPerformed

    private void TT27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT27ActionPerformed

    private void TT28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT28ActionPerformed

    private void jTextField28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField28ActionPerformed

    private void TT30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT30ActionPerformed

    private void TT31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT31ActionPerformed

    private void TT32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT32ActionPerformed

    private void TT40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT40ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT40ActionPerformed

    private void TT41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT41ActionPerformed

    private void TT42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT42ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT42ActionPerformed

    private void TT50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT50ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT50ActionPerformed

    private void TT51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT51ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT51ActionPerformed

    private void TT52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT52ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT52ActionPerformed

    private void TT60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT60ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT60ActionPerformed

    private void TT61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT61ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT61ActionPerformed

    private void TT62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT62ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT62ActionPerformed

    private void TT70ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT70ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT70ActionPerformed

    private void TT71ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT71ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT71ActionPerformed

    private void TT72ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT72ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT72ActionPerformed

    private void TT80ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT80ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT80ActionPerformed

    private void TT81ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT81ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT81ActionPerformed

    private void TT33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT33ActionPerformed

    private void TT34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT34ActionPerformed

    private void TT35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT35ActionPerformed

    private void TT36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT36ActionPerformed

    private void TT37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT37ActionPerformed

    private void TT43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT43ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT43ActionPerformed

    private void TT44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT44ActionPerformed

    private void TT45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT45ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT45ActionPerformed

    private void TT53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT53ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT53ActionPerformed

    private void TT54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT54ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT54ActionPerformed

    private void TT55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT55ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT55ActionPerformed

    private void TT46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT46ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT46ActionPerformed

    private void TT38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT38ActionPerformed

    private void TT47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT47ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT47ActionPerformed

    private void TT48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT48ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT48ActionPerformed

    private void TT56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT56ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT56ActionPerformed

    private void TT57ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT57ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT57ActionPerformed

    private void TT58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT58ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT58ActionPerformed

    private void TT82ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT82ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT82ActionPerformed

    private void TT63ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT63ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT63ActionPerformed

    private void TT64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT64ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT64ActionPerformed

    private void TT65ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT65ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT65ActionPerformed

    private void TT73ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT73ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT73ActionPerformed

    private void TT74ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT74ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT74ActionPerformed

    private void TT83ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT83ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT83ActionPerformed

    private void TT84ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT84ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT84ActionPerformed

    private void TT75ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT75ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT75ActionPerformed

    private void TT85ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT85ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT85ActionPerformed

    private void TT66ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT66ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT66ActionPerformed

    private void TT67ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT67ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT67ActionPerformed

    private void TT68ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT68ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT68ActionPerformed

    private void TT76ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT76ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT76ActionPerformed

    private void TT77ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT77ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT77ActionPerformed

    private void TT78ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT78ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT78ActionPerformed

    private void TT86ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT86ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT86ActionPerformed

    private void TT87ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT87ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT87ActionPerformed

    private void TT88ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TT88ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TT88ActionPerformed

    private void CheckButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckButtonActionPerformed
   
    }//GEN-LAST:event_CheckButtonActionPerformed

    private void QuitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuitButtonActionPerformed

    private void RestartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestartButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RestartButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sudoku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sudoku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sudoku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sudoku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sudoku().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CheckButton;
    private javax.swing.JLabel MainLableS2;
    private javax.swing.JPanel PanelGame;
    private javax.swing.JButton QuitButton;
    private javax.swing.JButton RestartButton;
    private javax.swing.JTextField TT00;
    private javax.swing.JTextField TT01;
    private javax.swing.JTextField TT02;
    private javax.swing.JTextField TT03;
    private javax.swing.JTextField TT04;
    private javax.swing.JTextField TT05;
    private javax.swing.JTextField TT06;
    private javax.swing.JTextField TT07;
    private javax.swing.JTextField TT08;
    private javax.swing.JTextField TT10;
    private javax.swing.JTextField TT11;
    private javax.swing.JTextField TT12;
    private javax.swing.JTextField TT13;
    private javax.swing.JTextField TT14;
    private javax.swing.JTextField TT15;
    private javax.swing.JTextField TT16;
    private javax.swing.JTextField TT17;
    private javax.swing.JTextField TT18;
    private javax.swing.JTextField TT20;
    private javax.swing.JTextField TT21;
    private javax.swing.JTextField TT22;
    private javax.swing.JTextField TT23;
    private javax.swing.JTextField TT24;
    private javax.swing.JTextField TT25;
    private javax.swing.JTextField TT26;
    private javax.swing.JTextField TT27;
    private javax.swing.JTextField TT28;
    private javax.swing.JTextField TT30;
    private javax.swing.JTextField TT31;
    private javax.swing.JTextField TT32;
    private javax.swing.JTextField TT33;
    private javax.swing.JTextField TT34;
    private javax.swing.JTextField TT35;
    private javax.swing.JTextField TT36;
    private javax.swing.JTextField TT37;
    private javax.swing.JTextField TT38;
    private javax.swing.JTextField TT40;
    private javax.swing.JTextField TT41;
    private javax.swing.JTextField TT42;
    private javax.swing.JTextField TT43;
    private javax.swing.JTextField TT44;
    private javax.swing.JTextField TT45;
    private javax.swing.JTextField TT46;
    private javax.swing.JTextField TT47;
    private javax.swing.JTextField TT48;
    private javax.swing.JTextField TT50;
    private javax.swing.JTextField TT51;
    private javax.swing.JTextField TT52;
    private javax.swing.JTextField TT53;
    private javax.swing.JTextField TT54;
    private javax.swing.JTextField TT55;
    private javax.swing.JTextField TT56;
    private javax.swing.JTextField TT57;
    private javax.swing.JTextField TT58;
    private javax.swing.JTextField TT60;
    private javax.swing.JTextField TT61;
    private javax.swing.JTextField TT62;
    private javax.swing.JTextField TT63;
    private javax.swing.JTextField TT64;
    private javax.swing.JTextField TT65;
    private javax.swing.JTextField TT66;
    private javax.swing.JTextField TT67;
    private javax.swing.JTextField TT68;
    private javax.swing.JTextField TT70;
    private javax.swing.JTextField TT71;
    private javax.swing.JTextField TT72;
    private javax.swing.JTextField TT73;
    private javax.swing.JTextField TT74;
    private javax.swing.JTextField TT75;
    private javax.swing.JTextField TT76;
    private javax.swing.JTextField TT77;
    private javax.swing.JTextField TT78;
    private javax.swing.JTextField TT80;
    private javax.swing.JTextField TT81;
    private javax.swing.JTextField TT82;
    private javax.swing.JTextField TT83;
    private javax.swing.JTextField TT84;
    private javax.swing.JTextField TT85;
    private javax.swing.JTextField TT86;
    private javax.swing.JTextField TT87;
    private javax.swing.JTextField TT88;
    private javax.swing.JTextField jTextField28;
    // End of variables declaration//GEN-END:variables
}
